sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script: 'if [ -n "${BABEL-}" ]; then make bootstrap-babel ; fi'

script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -n "${FLOW-}" ]; then npm run flow ; fi'
  - 'if [ -n "${BABEL-}" ]; then make test-babel ; fi'
  - 'if [ -z "${LINT-}" ] && [ -z "${FLOW-}" ] && [ -z "${BABEL-}" ]; then npm run test-ci ; fi'

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
    - node_js: "node"
      env: FLOW=true
    - node_js: "node"
      env: BABEL=true

after_success: 'if [ -z "${LINT-}" ] && [ -z "${FLOW-}" ] && [ -z "${BABEL-}" ]; then npm run coverage ; fi'

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
